#-------------------------------------------------------------------------------
#
# TravisCI Configuration, https://docs.travis-ci.com/.
#
# Supports running npm based test suite on multiple node versions to ensure
# backwards compatibility is retained.
#
#-------------------------------------------------------------------------------
---
language: node_js

# Run scripts without elevated access.
sudo: false

node_js:
  - "10"
  - "12"

cache:
  directories:
    - "node_modules"

before_install:
  - "npm install -g npm@latest"

before_script:
  # Install npm dependencies and skip dependency audit as we will run this
  # explicitly later.
  - "npm install --no-audit"

script:
  - "npm audit"
  - "npm run test"
