#
# TravisCI Configuration, https://docs.travis-ci.com/.
#
# Supports running npm based test suite with Code Climate integration for code coverage reporting.
#

language: node_js
sudo: false

node_js:
- '8'
- '9'
- '10'

cache:
  directories:
  - 'node_modules'

before_script:
- 'npm install'

script: 'npm run test'
